# -*- coding: utf-8 -*-
"""Template_mini_projet_SD_MNPI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OrA00rHbijFJiaZVvmM_2cBJj5P7j3sh

# Mini projet : Systèmes dynamiques & Méthodes numériques pour l'ingénieur

# **Modélisation et dynamique d'une épidémie, COVID-19 avec et sans confinement -Cas du Maroc-**
**Membres du groupe:**

 * **KADIRI Hiba**      :  Analyse numérique / Etude théorique du système avec confinement / Résultats et Discussion.
 * **ELHOUARI Nada**    :  Modélisation du problème / Etude théorique du système sans confinement / Vérification des résultats.
 * **HIRAJI Younes**    :  Etude théorique du sysème avec confinement.
 * **ELFARSI Latifa**   :  Etude théorique du système avec confinement.
 * **LAABYDY Mohamed**  :  Analyse numérique / Etude théorique du système avec confinement / Algorithme et implémentation.

# 0. Modélisation :

Ce projet présente un modèle mathématique SIR (L'acronyme SIR fait référence aux trois compartiments principaux du modèle : Susceptible (S), Infecté (I) et Retiré ou Rétabli (R)) visant à analyser la dynamique de propagation du Covid-19 tout en prenant en compte l'impact du confinement sur la population susceptible et de l'isolement de la population infectieuse. \\

\
L'un des paramètres clés que nous évaluons est le nombre de reproduction de base, $R_0$ , qui représente le nombre moyen de nouveaux cas engendrés par un individu infectieux typique au sein d'une population totalement composée d'individus susceptibles, pendant sa période d'infection. Cette étude se concentre spécifiquement sur le contexte du Maroc en utilisant ledit modèle.

**Le modèle SIR :** \\
Le modèle SIR suppose que la population totale reste constante, ce qui signifie qu'il n'y a pas de naissances ou de décès pris en compte. Il utilise des équations différentielles pour décrire les taux de changement des populations dans chaque compartiment en fonction de paramètres tels que le taux de transmission de la maladie et le taux de récupération. \\
\
Ce modèle permet d'étudier la dynamique de propagation d'une maladie, d'estimer l'impact des interventions (comme la vaccination ou le confinement) et de prévoir l'évolution de l'épidémie dans une population donnée.

Nous proposons un modèle SIR qui étend le modèle classique de Kermack et McKendrick $[4, 5, 6, 1]$  en tenant compte de l'effet du confinement sur les deux populations, les susceptibles et les infectieuses. Nous supposons également que $0 ≤ α < 1$  et $0 ≤ δ < 1$  sont les taux de confinement des susceptibles et d'isolement des infectieuses respectivement. Ainsi, la fraction des susceptibles confinés (protégés) est $αS$ , tandis que la fraction des susceptibles non confinés est $(1 − α) S$ , représentant la fraction des susceptibles d'être infectés par la fraction des infectieuses non confinées $(1 − δ)I$  à un taux d'infection égal à $δ$ . La fraction $δI$ est confinée. Λ représente la densité de naissances des susceptibles. La population $R$ comprend les individus retirés de la chaîne de transmission, y compris ceux confinés $(αS)$ , ceux isolés $(δI)$ , les personnes guéries et les personnes décédées.

\begin{cases}
\frac{dS}{dt}= Λ- β(1-α)(1-δ)SI-αS \\
\
\frac{dI}{dt}= β(1-α)(1-δ)SI-γI-δI\\
\frac{dR}{dt}=γI+αS+δI \\
\
N=S+I+R= constante → si Λ=0\\
S(0) > 0 , I(0) > 0 , R(0) > 0\\
\end{cases}

####Dans la première partie on va évaluer un système d'équation sans confinement.
\begin{cases}
\frac{dS}{dt}=- βSI\\
\frac{dI}{dt}=βSI - γI
\end{cases} \\


####Et dans la deuxième partie on va s'intéresser à l'évolution de la maladie avec confinement.
\begin{cases}
\frac{dS}{dt}=Ʌ - β.(1-α).(1-δ).SI-α.S\\
\frac{dI}{dt}= β.(1-α).(1-δ).SI - γI- δI
\end{cases} \\

# 1. Etude théorique (module système dynamique)

### **1.Evolution de la maladie sans confinement :**

L’étude se fera sur le système qu’on a déjà défini pour le cas sans confinement et avec les mêmes hypothèses (nous supposons que le confinement n’est pas encore déclaré, α = δ = 0, nous supposons aussi que le nombre de naissances est négligeable, Λ = 0) : \\
\begin{cases}
\frac{dS}{dt}=- βSI\\
\frac{dI}{dt}=βSI - γI
\end{cases} \\
En se basant sur des analyses épidémiologiques et des ajustements de modèle aux données observées de l'évolution de la maladie dans le Maroc,on prend : β = 0.17 et γ=0,146 \\
**•	Etude de l’existence :** \\
En vertu du théorème de Cauchy-Lipschitz, nous avons l’existence d’une solution du système ; étudions maintenant les points d’équilibre. \\
**•	Les points d’équilibre et leur stabilité :** \\
On a le système: 
\begin{cases}
\frac{dS}{dt}=- 0,17 SI\\
\frac{dI}{dt}=0,17 SI - 0,146 I
\end{cases} \\
Donc les points d’équilibre sont : (0 ; 0) et (0 ; 0,86)
Etudions maintenant la stabilité de ses deux points : \\
On commence par calculer la matrice jacobienne : \\
$J =\begin{pmatrix}
-0,17I & -0,17S  \\
0.17I-0.146 & 0.17S-0.146  \\
\end{pmatrix}$

**Pour le point d'équilibre (0 ; 0) :** \\
$J(0,0) =\begin{pmatrix}
0 & 0  \\
-0.146 & -0.146  \\
\end{pmatrix}$ \\
Les valeurs propres de J (0,0) sont les solutions de l'équation caractéristique $det(J(0,0) - λI) = 0$ , où I est la matrice identité. \\
En résolvant cette équation, nous obtenons les valeurs propres suivantes : \\
$λ_1 = 0 \\
λ_2 = -0.292$ \\
La valeur propre $λ_1 = 0$ indique une stabilité marginale et la valeur propre $λ_2 = -0.292$ a une partie réelle négative, ce qui indique que le point d'équilibre $(0,0)$ est un point d'équilibre instable.

**Pour le point d'équilibre (0 ; 0,86) :** \\
$J(0,0.86) =\begin{pmatrix}
0 & -0,146  \\
0 & -0.146  \\
\end{pmatrix}$ \\
Les valeurs propres de $J (0,0.86)$ sont les solutions de l'équation caractéristique $det(J(0,0.86) - λI) = 0$ , avec I la matrice identité.\\
En résolvant cette équation, nous obtenons les valeurs propres suivantes : \\
$λ_1 = 0 \\
λ_2 = -0.146$ \\
Donc, le point d'équilibre (0,0.86) est un point d'équilibre instable avec une stabilité marginale le long de la direction associée à la valeur propre $λ_1 = 0$.

**Portrait de phase :** \\
Nous allons maintenant tracer le portrait de phase du système pour visualiser les trajectoires et les comportements des variables dans le plan $(S, I)$.
"""

import numpy as np
import matplotlib.pyplot as plt

# Définition des équations différentielles
def dS_dt(S, I):
    return -0.17 * S * I

def dI_dt(S, I):
    return 0.17 * S * I - 0.146 * I

# Définition des points d'équilibre
def find_equilibrium():
    S_eq = []
    I_eq = []

    # Résolution des équations pour dS_dt = 0 et dI_dt = 0
    for S in np.linspace(0, 1, 100):
        for I in np.linspace(0, 1, 100):
            if abs(dS_dt(S, I)) < 0.01 and abs(dI_dt(S, I)) < 0.01:
                S_eq.append(S)
                I_eq.append(I)

    return S_eq, I_eq

# Calcul des points d'équilibre
S_eq, I_eq = find_equilibrium()

# Plage de valeurs de S et I
S = np.linspace(0, 1, 20)
I = np.linspace(0, 1, 20)

# Création de la grille de valeurs
S, I = np.meshgrid(S, I)

# Calcul des dérivées dS et dI sur la grille de valeurs
dS = dS_dt(S, I)
dI = dI_dt(S, I)

# Tracé des portraits de phase avec flèches vers les points d'équilibre
plt.quiver(S, I, dS, dI)
plt.scatter(S_eq, I_eq, color='red')
plt.xlabel('S')
plt.ylabel('I')
plt.title('Portrait de phase du système')

# Ajout des flèches
for i in range(len(S_eq)):
    plt.annotate("", xy=(S_eq[i], I_eq[i]), xytext=(S_eq[i]+0.1, I_eq[i]), arrowprops=dict(arrowstyle="->", lw=1.5))

plt.grid()
plt.show()

"""### **2.Evolution de la maladie avec confinement :**

Dans ce paragraphe, nous examinons le modèle $(1.1)$ avec les paramètres de confinement $α>0$ et $δ>0$ . \\
Nous nous concentrons sur l'étude du système SI car la population du compartiment R depend des population $S$ et $I$ , tel que $S$ et $I$ independents de $R$ . \\
Supposons que $Λ>0$ pour prendre en compte les nouvelles naissances pendant la durée de l'épidémie. \\
Le système de départ devient : \\
\begin{cases}
\frac{dS}{dt}=Ʌ - β.(1-α).(1-δ).SI-α.S\\
\frac{dI}{dt}= β.(1-α).(1-δ).SI - γI- δI
\end{cases} \\
En tenant compte de la dynamique de propagation du coronavirus au Maroc avec confinement, les valeurs de β et γ  ont été choisies pour modéliser une transmission relativement intense du virus et un taux de guérison moyen : \\
$β=1.25$ et $γ=1$

####**Point d'équilibre du système :** 
On résout ce système algébrique. on annule les dérivées de $S(t)$ et de $I(t)$ . \\
On constate deux cas : \\

**Le point d'équilibre sans maladie :** \\
On a $I(t) = 0 $ , $ \frac{dS}{dt}=0 $, $\frac{dI}{dt}=0$ \\
$Λ-β(1-α)(1_δ).0.I- αS = 0$ \\
⇒ $S=\frac{Λ}{α}$ \\
D'où le point d'équilibre est $E_0=(\frac{Λ}{α},0)$

**Le point d'équilibre avec maladie:** \\
$ \frac{dS}{dt}=0 $, $\frac{dI}{dt}=0$ \\

\begin{cases}
Λ-β(1-α)(1_δ).S^{\ast}.I^{\ast} αS^{\ast} = 0 \\
β(1-α)(1-δ)S^{\ast}.I^{\ast} - αS^{\ast} - γI^{\ast} - δI^{\ast} = 0
\end{cases} \\

\begin{cases}
S^{\ast}=\frac{γ+δ}{β.(1-α).(1-δ)}\\ 
\\
I^{\ast}=\frac{Λ-α.S^{\ast}}{β.(1-α).(1-δ).S^{\ast}} = \frac{Λ-α.S^{\ast}}{γ+δ} 
\end{cases} \\

d'où $E^{\ast}=(S^{\ast},I^{\ast})$ \\
$E^{\ast}$ est positif si $Λ-α.S^{\ast} > 0$ \\
⇒ $ Λ > \frac{α(γ+δ)}{β(1-α)(1-δ)} $ \\
\
⇒ $ \frac{γβ(1-α)(1-δ)}{γ+δ} > 1 $ \\
\
Posons $R_0=\frac{γβ(1-α)(1-δ)}{γ+δ}$

On fait la disjonction des deux cas : $R_0 < 1$ et $R_0 > 1$.

**Premier cas: suposons que $R_0  < 1$ , alors:** \\

on a $E^{\ast}$ est négatif, donc $E^{\ast}$ n'existe pas \\
donc le point d'équilibre sans maladie $E_0$ est le seul point d'équilibre du système.\\
**Etudions la stabilité de $E_0$ : ** \\
d'abord calculons la jacobienne: \\

$J(E)=\begin{pmatrix}
\ - β(1- α)(1- δ)I-α &  -β(1- 𝛂)(1-δ)S \\
β(1-α)(1-δ)I & β(1-α)(1-δ)S-γ-δ \\
\end{pmatrix}$ \\
\
calculons $J(E_0)$: \\
$J(E_0)=\begin{pmatrix}
\ -α & \frac{-β(1-α)(1-δ)𝚲}{α} \\
0 &  \frac{β(1-α)(1-δ)𝚲}{α} - γ -δ \\
\end{pmatrix}$ \\
le polynome caractéristique de cette matrice: 
det(λI-J($E_0$)) a pour solutions: \\
 $λ_1=-α$ \\

 $λ_2 = \frac{β(1-α)𝚲}{α}-γ-δ $ \\
$λ_1<0$ et $λ_2<0$ \\
donc le point d'équilibre $E_0$ est localement asymptotiquement stable

**Deuxieme cas: supposons que $R_0>1$, alors:** \\
-Il est évident que le point d'équilibre sans maladie $E_0$ est instable  \\
-Pour le point d'équilibre avec maladie; \\
calculons la jacobienne de $E^{\ast}$ \\
$J(E^{\ast}) =\begin{pmatrix}
\ -β(1-α)(1-δ)I^{\ast}-α & -(γ+δ) \\
β(1-α^)(1-δ)I^{\ast} & 0 \\
\end{pmatrix}$  \\
\
Comme $tr(J(E^{\ast})) < 0$ et $det(J(E^{\ast}))>0$ \\

\

donc $E^{\ast}$ est un point d'équilibre localement asymptotiquement stable.

**Portrait de phase :** \\
Dans cette partie nous allons tracer le portrait de phase de notre système.
"""

import numpy as np
import matplotlib.pyplot as plt

# Définir les paramètres du système
alpha = 0.2
beta = 0.5
gamma = 0.3
delta = 0.1
Ʌ = 1
# Définir les équations différentielles du système
def dS_dt(S, I):
    return Ʌ - beta * (1 - alpha) * (1 - delta) * S * I - alpha * S

def dI_dt(S, I):
    return beta * (1 - alpha) * (1 - delta) * S * I - gamma * I - delta * I

# Définir les points d'équilibre
equilibrium_points = [(Ʌ / (beta * (1 - alpha) * (1 - delta))), (Ʌ / (beta * (1 - alpha) * (1 - delta) * gamma + delta))]

# Définir la fonction pour calculer les dérivées des variables
def derivatives(variables, t):
    S, I = variables
    dSdt = dS_dt(S, I)
    dIdt = dI_dt(S, I)
    return [dSdt, dIdt]

# Définir les valeurs pour la grille du portrait de phase
S_values = np.linspace(0, 2, 20)
I_values = np.linspace(0, 2, 20)

# Créer la grille du portrait de phase
S_grid, I_grid = np.meshgrid(S_values, I_values)

# Calculer les dérivées sur la grille
dSdt_grid, dIdt_grid = derivatives([S_grid, I_grid], 0)

# Tracer le portrait de phase
plt.figure(figsize=(8, 6))
plt.quiver(S_grid, I_grid, dSdt_grid, dIdt_grid, scale=20)
plt.xlabel('S')
plt.ylabel('I')
plt.title('Portrait de phase')
plt.grid()
plt.xlim([0, 2])
plt.ylim([0, 2])


# Définir les points d'équilibre
equilibrium_points = [(Ʌ / (beta * (1 - alpha) * (1 - delta))), (Ʌ / (beta * (1 - alpha) * (1 - delta) * gamma + delta))]

# Tracer les points d'équilibre
for point in equilibrium_points:
    plt.plot(point, 0, 'ro')
    plt.text(point, 0, f'({point:.2f}, 0)', ha='center', va='bottom')


# Afficher le graphique
plt.show()

"""# 2. Analyse numérique (module méthode numérique pour l’ingénieur)

Le problème s'écrit :
\begin{cases}
\frac{dS}{dt}=Ʌ - β.(1-α).(1-δ).SI-α.S\\
     S(0)=N
\end{cases}

**Pour le schéma d'Euler explicite:**

Soit h le pas du temps. \\
$ S(t_n+h)=S(t_n)+h.\dot{S}(t_n)
= S(t_n)+h.(Ʌ - β.(1-α).(1-δ).S(t_n)I-α.S(t_n))\\
= S(t_n).(Ʌ-hA-hα)+hɅ$ \\
avec  $A= β.(1-α).(1-δ).I$

$S_1= S_0(1-hA-hα)+hɅ \\
S_2= S_1(1-hA-hα)+hɅ \\
S_2= S_0(1-hA-hα)^2 +hɅ(1-hA-hα)+ hɅ \\
S_3= S_0(1-hA-hα)^3 +hɅ(1-hA-hα)^2+ hɅ(1-hA-hα)+ hɅ \\ $

Alors on trouve l'expression récurrente suivante: \\
$ S_n=S_0(1-hA-hα)^n + \sum_{k=0}^{n-1} hɅ(1-hA-hα)^k $ \\
C'est le schéma d'Euler explicite.

On perturbe la condition initiale $S_0$ avec $S̃_0=S_0+ϵ$ \\
$ S̃=(S_0+ϵ).(1-Ah-hα)^n + \sum_{k=0}^{n-1} hɅ(1-hA-hα)^k \\
= S_n + ϵ(1-hA-hα)^n $ \\
Alors $ | S̃_n - S_n |= ϵ|1-hA-hα|^n $ avec $ ϵ > 0$ \\
Le schéma d'Euler reste stable après perturbation de la donnée initiale lorsque \\ $|1- Ah - α h |^n < 1 $ \\
c-à-d $ 0 < h < \frac{2}{A+α} $ \\
Pour étudier la convergence de ce schéma, nous devons vérifier si la solution numerique $S_n$ converge vers la solution exacte $y$ lorsque le pas h tend vers 0. \\
L'erreur: $ ϵ=y-S_n $ \\
Or le schéma d'Euler  explicite a une convergence d'ordre 1, d'où cela signifie que $ ϵ(t)= 𝙾(h) $ alors on peut déduire que $\lim_{h \to a} ϵ = 0 $ \\
Et par suite le schéma est convergent.

La condition de stabilité nous a permis de choisir une valeur de $h = 1$ \\
Le schéma d'Euler explicite peut être représenté comme suit :
"""

import numpy as np
import matplotlib.pyplot as plt

def euler_explicit(A, alpha, N, n, h,Ʌ):
    S = np.zeros(n+1)
    S[0] = N
    
    for k in range(n):
        S[k+1] = S[k] + h * (Ʌ - A*S[k] - alpha*S[k])
    
    return S

# Paramètres du système
Ʌ = 1
A = 2
alpha = 0.5
N = 34000000
n = 200
h = 1

# Calcul du schéma d'Euler explicite
S = euler_explicit(A, alpha, N, n, h,Ʌ)

# Tracé du schéma d'Euler explicite
t = np.arange(0, n+1) * h
plt.plot(t, S)
plt.xlabel('Temps')
plt.ylabel('Population (S)')
plt.title('Schéma d\'Euler explicite')
plt.show()

"""**Pour le schéma d'Euler implicite:**

Soit h le pas du temps.
\begin{cases}
S(t_n+h)=S(t_n)+h(Ʌ - β.(1-α).(1-δ).SI-α.S) \\
     S(t_0)=N
\end{cases} \\

⇒
\begin{cases}
(1+Ah+αh) S_{n+1} = S_n +hɅ \\
     S(t_0)=N
\end{cases} \\

⇒ $ S_{n+1} = \frac{S_n}{1+Ah+αh} +\frac{hɅ}{1+Ah+αh} $

$ S_1 = \frac{S_0}{1+Ah+αh} +\frac{hɅ}{1+Ah+αh} $ \\
$ S_2 = \frac{S_1}{1+Ah+αh} +\frac{hɅ}{1+Ah+αh} $ \\
$ S_2 = \frac{S_0}{(1+Ah+αh)^2} +\frac{hɅ}{(1+Ah+αh)^2} +\frac{hɅ}{1+Ah+αh} $ \\
D'où on déduit l'expression récurrente du schéma implicite: \\

$ S_n = \frac{S_0}{(1+Ah+αh)^n} +∑_{k=1}^n \frac{hɅ}{(1+Ah+αh)^k} $ \\
⇒
C'est le schéma d'Euler implicite.

**Etude de la convergence :** \\
L'objectif est de vérifier si $S_n$ converge vers la solution exacte du système lorsque h → 0 . \\
on tend h vers 0 : \\
$\lim_{h \to 0} S_n = \lim_{h \to 0} \frac{S_0}{(1+Ah+αh)^n} +\lim_{h \to 0} ∑_{k=1}^n \frac{hɅ}{(1+Ah+αh)^k} $ \\
$ = S_0 + 0 = S_0 $ \\
Lorsque h tend vers 0, le schéma d'Euler implicite converge bien vers la valeur initiale $S_0$. \\
On déduit que ce schéma est convergent.
"""

import numpy as np
import matplotlib.pyplot as plt

# Définition des paramètres
A = 2
alpha = 0.5
N = 34000000
h = 0.1
n = 200
Ʌ = 1 
# Définition de la fonction f(S) = 1 - AS - alpha*S
def f(S):
    return Ʌ - A*S - alpha*S

# Schéma d'Euler implicite
def euler_implicit(S0, h, n,Ʌ):
    S = [S0]  # Liste pour stocker les valeurs de S
    for i in range(1, n+1):
        S.append(S[i-1] / (1 + h*A + alpha*h) + h*f(S[i-1]))
    return S

# Calcul des valeurs de S en utilisant le schéma d'Euler implicite
S_values = euler_implicit(N, h, n,Ʌ)

# Création du vecteur temps
t = np.linspace(0, n*h, n+1)

# Tracé de la solution obtenue
plt.plot(t, S_values, label='Euler implicite')
plt.xlabel('Temps')
plt.ylabel('S')
plt.title('Schéma d\'Euler implicite')
plt.legend()
plt.show()

"""### **Nous préférons utiliser le schéma explicite en raison de sa précision supérieure. Les schémas explicites offrent un contrôle précis de la précision en ajustant le pas de temps. En augmentant le nombre d'itérations ou en réduisant le pas de temps, nous pouvons obtenir des résultats plus précis. Cela nous permet de répondre aux exigences spécifiques du problème et d'obtenir une précision plus élevée lorsque nécessaire. De plus, la simplicité de mise en œuvre des schémas explicites facilite l'ajustement du pas de temps et la gestion de la précision. Par conséquent, compte tenu de l'importance que nous accordons à la précision des résultats, nous optons pour le schéma explicite.**

# 3. Implémentation (Code Python)
"""

import numpy as np
from scipy.integrate import odeint
import time
import matplotlib.pyplot as plt

"""**L'algorithme proposé pour la résolution du système :**"""

def euler_explicit_solver(A, alpha, N, n, h):
    S = np.zeros(n+1)
    S[0] = N
    
    for k in range(n):
        S[k+1] = S[k] + h * (1 - A*S[k] - alpha*S[k])
    
    return S

"""**pour comparer cette méthode avec la fonction odeint de la bibliothèque SciPy**"""

def odeint_solver(A, alpha, N, t):
    def system(S, t):
        return Ʌ - A*S - alpha*S
    
    S0 = N
    S = odeint(system, S0, t)
    
    return S.flatten()

# Paramètres du système
A = 2
alpha = 0.5
N = 34000000
n = 200
h = 0.1
Ʌ = 1

# Temps d'échantillonnage
t = np.arange(n+1) * h

# Résolution avec Euler explicite
start_time = time.time()
S_euler = euler_explicit_solver(A, alpha, N, n, h)
euler_time = time.time() - start_time

# Résolution avec odeint
start_time = time.time()
S_odeint = odeint_solver(A, alpha, N, t)
odeint_time = time.time() - start_time

# Comparaison des résultats
error = np.abs(S_euler - S_odeint)

print("Erreur maximale : ", np.max(error))
print("Temps de calcul (Euler explicite) : ", euler_time)
print("Temps de calcul (odeint) : ", odeint_time)

"""## **Commentaire :** 
Dans ce script, nous utilisons la fonction odeint de la bibliothèque SciPy pour résoudre le système différentiel. Nous comparons ensuite les résultats obtenus avec les deux méthodes (Euler explicite et odeint) en calculant l'erreur maximale entre les deux solutions numériques. De plus, nous mesurons également le temps de calcul pour chaque méthode.

## **Comparaison graphique :** 
Nous traçons parla suite les solutions obtenues avec les méthodes d'Euler explicite et odeint sur le même graphique. \\
Les solutions sont tracées en fonction du temps (t) et de la population (S).
"""

# Tracé des solutions
plt.plot(t, S_euler, label='Euler explicite')
plt.plot(t, S_odeint, label='odeint')
plt.xlabel('Temps')
plt.ylabel('Population (S)')
plt.title('Comparaison des solutions : Euler explicite vs odeint')
plt.legend()
plt.show()

"""# 4. Discussion

En résumé,  ce projet examine le rôle du confinement de la population susceptible et de l'isolement de la population infectieuse dans la gestion de la propagation des épidémies, en mettant particulièrement l'accent sur le **Covid-19 au Maroc**. L'étude analyse l'impact du nombre de reproduction de base, un facteur clé dans la transmission des épidémies. Pour traiter ce problème nous avons comparé les deux périodes, avant et après confinement : la période avant confinement marquée par l'apparition des cas locaux, et la période après confinement (à partir du 20 mars), caractérisée par la propagation plus large de l'épidémie au sein de la population. \\


Les résultats démontrent que pendant la phase initiale, le nombre cumulatif de personnes infectées augmente automatiquement. Cependant, lors de la phase ultérieure et grâce à la mise en place de mesures de confinement et d'isolement, le taux de transmission diminue par rapport à la phase initiale. Il est souligné que le nombre de reproduction de base est influencé par les taux de confinement et d'isolement. Une augmentation de ces taux conduit à une diminution du nombre de reproduction en dessous de 1, ce qui indique un contrôle réussi de l'épidémie, tandis que des taux plus bas conduisent à un nombre de reproduction supérieur à 1, ce qui signifie une propagation continue de la maladie. \\


**En conclusion, la gestion efficace d'une épidémie repose sur la capacité à réguler les taux de confinement pour la population susceptible et d'isolement pour les personnes infectées.**
"""